runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /assets
  static_dir: assets
  secure: always

- url: /(.*)
  static_files: index.html
  upload: index.html
  secure: always  