runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /css
  static_dir: css
  secure: always

- url: /work/trolley/a
  static_dir: work/trolley/a
  secure: always

- url: /work/trolley/b
  static_dir: work/trolley/b
  secure: always  

- url: /(.*)
  static_files: index.html
  upload: index.html
  secure: always  