runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /css
  static_dir: css
  secure: always

- url: /work
  static_dir: work
  secure: always

- url: /(.*)
  static_files: index.html
  upload: index.html
  secure: always  